static:
	make -C ../zad2 static
	../zad2/wc_repl_static < input.txt
	make -C ../zad2 clean

shared:
	make -C ../zad2 shared
	../zad2/wc_repl_shared < input.txt
	make -C ../zad2 clean

dynamic:
	make -C ../zad2 dynamic
	../zad2/wc_repl_dynamic < input.txt
	make -C ../zad2 clean